CREATE DATABASE RailwayDB;
USE RailwayDB;
DESCRIBE ukproject;

-- Count total number of records in the dataset
SELECT COUNT(*) AS Total_Records
FROM ukproject;

-- Display the first 10 rows to get an overview of the data
SELECT *
FROM ukproject
LIMIT 10;

-- Count distinct values in key categorical columns
SELECT 
    COUNT(DISTINCT PurchaseType) AS Unique_PurchaseTypes,
    COUNT(DISTINCT PaymentMethod) AS Unique_PaymentMethods,
    COUNT(DISTINCT TicketType) AS Unique_TicketTypes
FROM ukproject;

-- Count number of tickets for each ticket type
SELECT TicketType, COUNT(*) AS Ticket_Count
FROM ukproject
GROUP BY TicketType
ORDER BY Ticket_Count DESC;

-- Analyze usage of different railcards
SELECT Railcard, COUNT(*) AS Count
FROM ukproject
GROUP BY Railcard
ORDER BY Count DESC;

-- Identify the most frequently used ticket class
SELECT TicketClass, COUNT(*) AS Count
FROM ukproject
GROUP BY TicketClass
ORDER BY Count DESC;

-- Find the most commonly used payment methods
SELECT PaymentMethod, COUNT(*) AS Count
FROM ukproject
GROUP BY PaymentMethod
ORDER BY Count DESC;

-- Calculate revenue generated by each payment method
SELECT PaymentMethod, SUM(FinalRevenue) AS Total_Revenue
FROM ukproject
GROUP BY PaymentMethod
ORDER BY Total_Revenue DESC;

-- Calculate the average ticket price for each payment method
SELECT PaymentMethod, AVG(Price) AS AvgPrice
FROM ukproject
GROUP BY PaymentMethod;

-- Calculate total revenue across all transactions
SELECT SUM(FinalRevenue) AS Total_Revenue
FROM ukproject;

-- Revenue generated by each type of ticket
SELECT TicketType, SUM(FinalRevenue) AS Revenue
FROM ukproject
GROUP BY TicketType
ORDER BY Revenue DESC;

-- Compare revenue between weekday and weekend journeys
SELECT WeekType, SUM(FinalRevenue) AS Revenue
FROM ukproject
GROUP BY WeekType
ORDER BY Revenue DESC;

-- Revenue distribution based on discount levels
SELECT DiscountLevel, SUM(FinalRevenue) AS Revenue
FROM ukproject
GROUP BY DiscountLevel
ORDER BY Revenue DESC;

-- Count number of purchases per month
SELECT MONTH(DateofPurchase) AS Month, COUNT(*) AS Count
FROM ukproject
GROUP BY Month
ORDER BY Month;

-- Calculate daily revenue
SELECT DateofPurchase, SUM(FinalRevenue) AS DailyRevenue
FROM ukproject
GROUP BY DateofPurchase
ORDER BY DateofPurchase;

-- Identify peak purchase hours
SELECT PurchaseHour, COUNT(*) AS Count
FROM ukproject
GROUP BY PurchaseHour
ORDER BY Count DESC;

-- Count delayed journeys for each date
SELECT DateofJourney, COUNT(*) AS DelayedTrips
FROM ukproject
WHERE IsDelayed = 'Yes'
GROUP BY DateofJourney
ORDER BY DelayedTrips DESC;

-- Calculate average journey duration
SELECT AVG(`JourneyDuration (min)`) AS AvgDuration
FROM ukproject;

-- Calculate the percentage of delayed journeys
SELECT 
    (SUM(CASE WHEN IsDelayed = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100 
    AS Delay_Percentage
FROM ukproject;

-- Identify the top 5 most frequently used departure stations
SELECT DepartureStation, COUNT(*) AS Trip_Count
FROM ukproject
GROUP BY DepartureStation
ORDER BY Trip_Count DESC
LIMIT 5;

-- Calculate the average revenue for each ticket type
SELECT TicketType, AVG(FinalRevenue) AS Avg_Revenue
FROM ukproject
GROUP BY TicketType
ORDER BY Avg_Revenue DESC;

-- Count number of purchases for each day of the week
SELECT DayofWeek, COUNT(*) AS Purchase_Count
FROM ukproject
GROUP BY DayofWeek
ORDER BY Purchase_Count DESC;



